### ISSUE TITLE
Improve setting custom webmention endpoint URL

### ISSUE THREAD

**Issue by isellsoap** [gRegorLove/ProcessWire-Webmention#20]
<img width="613" alt="Bildschirmfoto 2020-06-10 um 13 27 57" src="https://user-images.githubusercontent.com/477474/84262667-47c9d680-ab1e-11ea-83e0-91e36dce14e3.png">

Instead of entering a hard-coded value you could use a page-select field here. The user would select the custom webmention url field from the page tree.

Maybe that would even help with multi-lang support.

 In a multi-language setup, the website would then have two distinct webmention endpoints, e.g. 

- for the first language (English) https://bla.com/webmention-endpoint/
- for the second language (German) https://bla.com/de/webmention-endpoint/

Just thinking out loud here. Also not considering multi-lang support here I think it would be an improvement to use a page select field for this setting.

**Comment by gRegorLove** [comment]
That's intended for external webmention endpoints, like https://webmention.io/. If you're not using one of those, this field should be left blank. When that field is blank, the plugin finds the endpoint with selector `template=webmention-endpoint` and adds the `Link` header for it. That means you can move the `webmention-endpoint` page anywhere in the page hierarchy and the headers will update automatically.

Generally I don't think it would be necessary / recommended to have multiple endpoints. Special handling of certain target URLs could be handled at a lower level (e.g. a hook in the plugin) and shouldn't require a separate endpoint.

With this plugin specifically, the webmentions are stored in a field on an individual page. Since translation URLs are actually special routing that maps back to the same page ID, received webmentions to any translation URL would be saved on the single, canonical page.

The more I think about it, I suspect this plugin will not currently handle webmentions to non-canonical language pages. If the canonical page is `https://example.com/de/post` and I send a webmention to `https://example.com/en/post`, the verification process is going to check that my source URL contains a link to the canonical URL -- which it doesn't.

**Comment by isellsoap** [comment]
I see, thanks for clarifying. 

I will do some testing regarding multi-lang page names on my website.

**Comment by gRegorLove** [comment]
@isellsoap I'm happy to test sending some webmentions to different translation URLs if you want to leave some sample links in this thread.

**Comment by isellsoap** [comment]
FYI: In the end I removed my multilang setup from my website, so this issue is no longer relevant for me. Thanks!
